# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 8 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          docker run -u root -v $(pwd)/.ccache:/ccache -v $(pwd):/workspace m0rf30/arch-arm-crosscompile:latest \
            bash -c "cd /workspace; CCACHE_DIR=/ccache ./build.sh"
          echo "KERNEL_VER=$(ls qemu_kernel* | cut -d"-" -f 2)" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "qemu-kernel-rpi-3-${{ env.KERNEL_VER }}"
          path: |
            qemu_kernel*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.KERNEL_VER }}"
          prerelease: false
          title: "qemu-kernel-rpi-3-${{ env.KERNEL_VER }}"
          files: |
            qemu_kernel*
